CREATE DATABASE tomatoes;

\c tomatoes

CREATE TABLE IF NOT EXISTS actors (
  id serial,
  lastname varchar(25) NOT NULL,
  firstname varchar(25) NOT NULL,
  role varchar(50) NOT NULL,
  movie varchar(50) NOT NULL,
  year int,
  PRIMARY KEY (id)
)  ;


INSERT INTO actors (lastname, firstname, role, movie, year) VALUES
( 'Firth', 'Colin', 'George', 'King''s Speech', 2010),
( 'Downey', 'Robert', 'Tony Stark', 'Iron Man 2', 2010),
( 'Paltrow', 'Gwyneth', 'Pepper Potts', 'Iron Man 2', 2010),
( 'Jackson', 'Samuel', 'Nick Fury', 'Iron Man 2', 2010),
( 'Downey', 'Robert', 'Tony Stark', 'Avengers', 2012),
( 'Jackson', 'Samuel', 'Nick Fury', 'Avengers', 2012),
( 'Jolie', 'Angelina', 'Evelyn Salt', 'Salt', 2010),
( 'Jolie', 'Angelina', 'Elise Clifton Ward', 'The Tourist', 2010),
( 'Jolie', 'Angelina', 'Tigress', 'Kung Fu Panda', 2008),
( 'Black', 'Jack', 'Po', 'Kung Fu Panda', 2008),
( 'Black', 'Jack', 'Jerry', 'Be Kind Rewind', 2008),
( 'Jolie', 'Angelina', 'Franky Cook', 'Sky Captain and the World of Tomorrow', 2004),
( 'Black', 'Jack', 'Jeff', 'Year of the Dog', 2007),
( 'Depp', 'Johnny', 'Frank Tupelo', 'The Tourist', 2010),
( 'Depp', 'Johnny', 'Jack Sparrow', 'Pirates of the Caribbean', 2003),
( 'Knightley', 'Keira', 'Elizabeth Swann', 'Pirates of the Caribbean', 2003),
( 'Page', 'Ellen', 'Ariadne', 'Inception', 2010),
( 'Page', 'Ellen', 'Juno MacGuff', 'Juno', 2007),
( 'DiCaprio', 'Leonardo', 'Cobb', 'Inception', 2010),
( 'DiCaprio', 'Leonardo', 'Frank Abagnate, Jr', 'Catch Me If You Can', 2002),
( 'DiCarprio', 'Leonardo', 'Billy Costigan', 'The Departed', 2006),
( 'Watanabe', 'Ken', 'Saito', 'Inception', 2010),
( 'Watanabe', 'Ken', 'Ra''s Al Ghul', 'Batman Begins', 2005),
( 'Bale', 'Christian', 'Bruce Wayne/Batman', 'Batman Begins', 2005),
( 'Holmes', 'Katie', 'Rachel Dawes', 'Batman Begins', 2005),
( 'Paltrow', 'Gwyneth', 'Polly Perkins', 'Sky Captain and the World of Tomorrow', 2004),
( 'Johansson', 'Scarlet', 'Black Widow', 'Iron Man 2', 2010),
( 'Johansson', 'Scarlet', 'Black Widow', 'Avengers', 2012),
( 'Johansson', 'Scarlet', 'Mindy the Mermaid', 'Spongebob Squarepants Movie', 2004),
( 'Paltrow', 'Gwyneth', 'Security Guard', 'Inception', 2010),
( 'Pelaez', 'Angelina', 'Sister Anna', 'Man on Fire', 2004),
( 'Palaez', 'Angelina', 'Donna Mercedes', 'Casa de los Babys', 2003),
( 'Jolie', 'Samantha', 'Amber Autumn', 'Hysterical Blindness', 2002),
( 'Black', 'Shane', 'director', 'Kiss, Kiss, Bang Bang', 2005),
( 'Back', 'Lucas', 'Oakley', 'Cold Mountain', 2003),
( 'Black', 'Karen', 'Mother Firefly', 'House of 1000 Corpses', 2002),
( 'Black', 'Karen', 'Luna', 'Hollywood Dreams', 2006),
( 'Page', 'Bruce', 'Jimmy''s Father', 'Mystic River', 2003),
( 'Downey', 'Roma', 'herself', 'Miracles and Visions', 1996),
( 'Cruz', 'Penelope', 'Angelica', 'Pirates of the Caribbean On Stranger Tides', 2011),
( 'Holmes', 'Katie', 'Tommy', 'Peaceful Warrior', 2006),
( 'Paltrow', 'Gwyneth', 'Pepper Potts', 'Avengers', 2012),
( 'Hoffman', 'Dustin', 'Master Shifu', 'Kung Fu Panda', 2008),
( 'Jolie', 'Angelina', 'Acid Burn', 'Hackers', 1995),
( 'Mori', 'Naoko', 'Tokyo Hacker', 'Hackers', 1995),
( 'Bale', 'Christian', 'Bruce Wayne/Batman', 'Dark Knight Rises', 2012),
( 'Hathaway', 'Anne', 'Selina', 'Dark Knight Rises', 2012),
( 'Damon', 'Matt', 'Mitch Emhoff', 'Contagion', 2011),
( 'Paltrow', 'Gwyneth', 'Beth Emhoff', 'Contagion', 2011),
( 'Paltrow', 'Gwyneth', 'Virginia "Pepper" Potts', 'Iron Man', 2008),
('Stuart', 'Katie', 'Kitty Pryde', 'X2: X-Men United', 2003),
('Stewart', 'Patrick', 'Professor Xavier', 'X2: X-Men United', 2003),
('Larson', 'Brie', 'Carol Danvers/Captain Marvel', 'Captain Marvel', NULL ),
('Jackson', 'Samuel', 'Nick Fury', 'Captain Marvel', NULL);
